### ISSUE TITLE
Add the tensorrt inference to the original mediapipe project

### ISSUE THREAD

**Issue by Gaozhongpai** [houmo-ai/mediapipe_plus#3]
Is it possible to add the tensorrt inference to the original mediapipe project for different demos, e.g., hand tracking, without changing the original pipeline for Ubuntu desktop and Jetson

**Comment by ajiang17** [comment]
I think its possible



---- 回复的原邮件 ----
| 发件人 | Zhongpai ***@***.***> |
| 日期 | 2022年11月16日 10:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [houmo-ai/mediapipe_plus] Add the tensorrt inference to the whole mediapipe project (Issue #3) |

Is it possible to add the tensorrt inference to the original mediapipe project for different demos, e.g., hand tracking.

**Comment by Gaozhongpai** [comment]
@ajiang17 I didn't see any updates for a long time. Are you still putting effort on this project?

**Comment by ajiang17** [comment]
Our company  is an ai chip .co
We will put effort on mediapipe in future but not now.



---- 回复的原邮件 ----
| 发件人 | Zhongpai ***@***.***> |
| 日期 | 2022年11月17日 06:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [houmo-ai/mediapipe_plus] Add the tensorrt inference to the original mediapipe project (Issue #3) |

@ajiang17 I didn't see any updates for a long time. Are you still putting effort on this project?
